services:
  ansible:
    container_name: ansible
    image: apurwasingh/cansible
    restart: unless-stopped
    networks:
      jnet:
        ipv4_address: 30.30.30.4
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    tty: true

  jenkins:
    container_name: jenkins
    image: apurwasingh/djentle
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      jnet:
        ipv4_address: 30.30.30.2
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

networks:
  jnet:
    driver: bridge
    ipam:
      config:
        - subnet: 30.30.30.0/24

volumes:
  jenkins_home:
    driver: local
